file-host: no freetz magic for maybe incompatible system binary

diff --git a/tools/path/file b/tools/path/file
--- a/tools/path/file
+++ b/tools/path/file
@@ -1,13 +1,14 @@
 #! /usr/bin/env bash
 MYOWN="$(realpath $0)"
 TOOLS="$(dirname $(dirname $MYOWN))"
-MGC="$TOOLS/build/usr/share/misc/magic.mgc"
+MYMGC="$TOOLS/build/usr/share/misc/magic.mgc"
 
 file="$TOOLS/build/usr/bin/file"
-[ -x "$file" ] && exec "$file" -m $MGC "$@"
+[ -x "$file" ] && exec "$file" -m $MYMGC "$@"
 
 file="$(which -a 'file' | grep -v "^$MYOWN$" | head -n1)"
-[ -x "$file" ] && exec "$file" -m $MGC "$@"
+[ -x "$file" ] && exec "$file" "$@"
 
-echo "Miserable failure, no file binary!" >&2
+echo "Miserable failure, no 'file' binary!" >&2
 exit 1
+
