freetz_download: add assets download

diff --git a/tools/freetz_download b/tools/freetz_download
--- a/tools/freetz_download
+++ b/tools/freetz_download
@@ -52,17 +52,52 @@ Debugging: just set DEBUG=1, like this:
 EOF
 }
 
+# Downloads a firmware asset from release
+# env: $FREETZ_DLTOKEN with read access
+# $1: file name of release
+# $2: destination file (if different from $1)
+do_assets() {
+	local DLT="${FREETZ_DLTOKEN}"
+	local GIT="images"
+	local TAG="firmware"
+	local SRC="${1##*/}"
+	local DST="${2:-${1}}"
+	echo 1>&11
+	[ -z "${DLT}" ] && echo "No TOKEN" 1>&11 && return 1
+	[ -e "${DST}" ] && echo "File already exists" 1>&11 && return 1
+
+	local ASSETS="$(curl -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer ${DLT}"  -H "X-GitHub-Api-Version: 2022-11-28"  "https://api.github.com/repos/Freetz-NG/${GIT}/releases/tags/${TAG}" 2>&12)"
+	[ -z "${ASSETS}" ] && echo "Download failed - No ASSETS" 1>&11 && return 1
+	local ASSID="$(echo "${ASSETS}" | grep -B7 "\"${SRC}\"" | sed -rn 's/ *"id": *([^,]*),*/\1/p')"
+	[ -z "${ASSID}" ] && echo "Download failed - No ASSID" 1>&11 && return 1
+	echo "Found ASSID:=${ASSID}" 1>&11
+
+	[ "$opt_trap_delete" == y ] && trap 'echo "Deleting file: \"${DST}\""; rm \"${DST\" 2>/dev/null; exit 1' TERM INT
+	curl -Lo "${DST}"    -H "Accept: application/octet-stream"     -H "Authorization: Bearer ${DLT}"  -H "X-GitHub-Api-Version: 2022-11-28"  "https://api.github.com/repos/Freetz-NG/${GIT}/releases/assets/${ASSID}" 1>&11 2>&12
+	curl_result=$?
+	[ "$opt_trap_delete" == y ] && trap - TERM INT
+
+	if [ "$curl_result" != "0" ]; then
+		echo "Download failed - \"${SRC}\"  ->  error code $curl_result" 1>&11
+		rm -f "$outFile"
+		return $curl_result
+	fi
+	echo "Download succeeded - \"${SRC}\"  ->  saved to folder \"${2%/*}\"" 1>&11
+}
+
 do_download() {
 	# $1 = target directory, $2 = download URL without file, $3 = (remote) file name
 	local outFile="${1%%/}/${opt_out_file:-$3}"
 	local fullURL="${2%%/}/$3"
-	[ "$opt_trap_delete" == y ] && trap 'echo "Deleting file: \"$outFile\""; rm "$outFile" 2>/dev/null; exit 1' TERM INT
 	echo 1>&11
+
+	[ "$opt_trap_delete" == y ] && trap 'echo "Deleting file: \"$outFile\""; rm "$outFile" 2>/dev/null; exit 1' TERM INT
 	[ "$DEBUG" == "1" ] && echo \
 	"wget $WGET_INSECURE_HTTPS --no-directories --tries=2 --timeout=3 --progress=bar:force:noscroll '${fullURL}' --output-document='${outFile}' 1>&11 2>&12"
 	 wget $WGET_INSECURE_HTTPS --no-directories --tries=2 --timeout=3 --progress=bar:force:noscroll "${fullURL}" --output-document="${outFile}" 1>&11 2>&12
 	wget_result=$?
 	[ "$opt_trap_delete" == y ] && trap - TERM INT
+
 	if [ "$wget_result" != "0" ]; then
 		if [ -e "/usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt" ]; then
 			# https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
@@ -302,6 +337,7 @@ enumerate_mirrors_official() {
 				done
 			elif [ ${url:0:4} == "@AVM" ]; then
 				subpath=${url/@AVM\//}
+				sites[${#sites[@]}]=DLTOKEN
 				sites[${#sites[@]}]=https://download.avm.de/fritzbox/$subpath
 				sites[${#sites[@]}]=https://download.avm.de/$subpath
 #				sites[${#sites[@]}]=https://download.avm.de/fritzwlan/$subpath
@@ -452,9 +488,10 @@ for i in ${sites[@]}; do
 			continue
 		fi
 	else
-		do_download "$DL_DIR" "$i" "$DL_FILE"
-		if [ "$?" != "0" ]; then
-			continue
+		if [ "$i" != "DLTOKEN" ]; then
+			do_download "$DL_DIR" "$i" "$DL_FILE" || continue
+		else
+			[ -n "${FREETZ_DLTOKEN}" ] && do_assets "$DL_FILE" "$DL_DIR/${opt_out_file:-$DL_FILE}" || continue
 		fi
 
 		local DL_DNF="$DL_DIR/${opt_out_file:-$DL_FILE}"
